### ISSUE TITLE
demo?

### ISSUE THREAD

**Issue by dcsan** [oilwer/LMS#1]
sorry to post on your nice clean issues but not sure who to contact. I'm looking for an open source javascript LMS to build on, and wondering if you have a demo install of this system anywhere, or any docs on its functionality, API etc?

**Comment by ph4t0o0o0om** [comment]
Hey @dcsan do you found something that open source LMS? Like there is a features of realtime whiteboard and a video conference? For collaboration? Please reply. Thank you!

**Comment by dcsan** [comment]
no, still looking.

**Comment by ph4t0o0o0om** [comment]
@dcsan Hmm do you have at least close to that? We can share resources I have a realtime collaborative whiteboard running on nodejs and socket.io   . We can exchange resources ;)

**Comment by dcsan** [comment]
i'm more looking for the basic LMS stuff like class management and course authoring, content management. the more interesting realtime stuff is what i want to work on... (and our use case is for mobile learning app, so not so much whiteboard)

**Comment by ph4t0o0o0om** [comment]
Okay. Do you find something like this " A virtual board for web" There is a whiteboard and video in realtime?

**Comment by warriv93** [comment]
Hello @dcsan Here is a link to the app running on Heroku: https://learningmadesimple.herokuapp.com/login 
And here is my fork where i added some additional stuff: https://github.com/warriv93/LMS 

Cool that you find use of our open source code :) 
Good luck!

**Comment by dcsan** [comment]
hi @warriv93 

thanks! I need to hook up to slack to create a course but can't see where to do that...


Username | Password
-- | --
student | student
teacher | teacher
admin


![image](https://user-images.githubusercontent.com/514002/44395231-cfbaa700-a56b-11e8-88bf-5beb5da81c2d.png)

**Comment by warriv93** [comment]
@dcsan  okey, you need to fork the code base and setup your own slack integration thing, and then put the keys in the code and then host it your self on heroku. (All the configs are done so just to push to a new repo of your heroku. )

**Comment by dcsan** [comment]
I'm not so concerned about the slack thing, but that's the only way to enable test driving creating or viewing any of the courses i think? there's no sample content in the system, and no way to create it without slack auth, and no way to auth slack as it stands.

thanks anyway
